<?php

namespace Database\Seeders;

use App\Models\Airline;
use Illuminate\Database\Seeder;

class AirlinesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->airlinesData() as $airline) {
            Airline::updateOrCreate(['name' => $airline[1]], [
                'thumbnail' => $airline[2],
            ]);
        }
    }

    protected function airlinesData()
    {
        return [
            [1, 'Blue Air', '0B.png'],
            [3, 'Ak Bars Aero', '2B.png'],
            [4, 'SNCF', '2C.png'],
            [5, 'Star Peru', '2I.png'],
            [6, 'Air Burkina', '2J.png'],
            [7, 'Avianca Ecuador', '2K.png'],
            [8, 'Helvetic Airways', '2L.png'],
            [9, 'PAL Express', '2P.png'],
            [10, 'Air Inuit', '3H.png'],
            [11, 'Air Arabia Maroc', '3O.png'],
            [12, 'Air Antilles Express', '3S.png'],
            [13, 'Caribbean Air Export Import Inc.', 'CB.png'],
            [14, 'Moldavian Airlines', '2M.png'],
            [15, 'Welcome Air', '2W.png'],
            [16, 'Jetstar Asia', '3K.png'],
            [17, 'Tiara Air Aruba', '3P.png'],
            [18, 'Sichuan Airlines', '3U.png'],
            [19, 'Warbelow\'s Air Ventures', '4W.png'],
            [20, 'Nextjet', '2N.png'],
            [21, 'Air Choice One', '3E.png'],
            [22, 'Intersky Luftfahrt', '3L.png'],
            [23, 'Avior Airlines', '3R.png'],
            [24, 'Air Sinai', '4D.png'],
            [25, 'LATAM Chile', 'LA.png'],
            [26, 'Gazpromavia', '4G.png'],
            [27, 'HOP!', 'A5.png'],
            [28, 'Okay Airways', 'BK.png'],
            [29, 'Air Botswana', 'BP.png'],
            [30, 'Cyprus Airways', 'CY.png'],
            [31, 'Etihad Airways', 'EY.png'],
            [32, 'FlyDamas', '4J.png'],
            [33, 'LATAM Argentina', '4M.png'],
            [34, 'Interjet', '4O.png'],
            [35, 'Safi Airways', '4Q.png'],
            [36, 'Belair Airlines', '4T.png'],
            [37, 'Germanwings', '4U.png'],
            [38, 'Nature Air', '5C.png'],
            [39, 'Air Algerie', 'AH.png'],
            [40, 'British Airways', 'BA.png'],
            [41, 'Biman Bangladesh Airlines', 'BG.png'],
            [42, 'airBaltic', 'BT.png'],
            [43, 'Air Jet', '7A.png'],
            [44, 'Fly540', '5H.png'],
            [45, 'ASL Airlines France', '5O.png'],
            [46, 'Israir Airlines', '6H.png'],
            [47, 'SmartLynx Airlines', '6Y.png'],
            [48, 'First Air', '7F.png'],
            [49, 'Nouvelair', 'BJ.png'],
            [50, 'Cebu Pacific', '5J.png'],
            [51, 'Tigerair Australia', 'TT.png'],
            [52, 'Canadian North', '5T.png'],
            [53, 'IndiGo', '6E.png'],
            [54, 'Alrosa', '6R.png'],
            [55, 'Tajik Air', '7J.png'],
            [56, 'Saratov Airlines', '6W.png'],
            [57, 'Maluti Sky', '7D.png'],
            [58, 'Insel Air', '7I.png'],
            [59, 'Aerocaribbean', '7L.png'],
            [60, 'Windrose Airlines', '7W.png'],
            [61, 'Wright Air Service', '8V.png'],
            [62, 'Jeju Air', '7C.png'],
            [63, 'Ravn Alaska', '7H.png'],
            [64, 'MetroJet', '7K.png'],
            [65, 'Federal Air', '7V.png'],
            [66, 'Lucky Air', '8L.png'],
            [67, 'Onur Air', '8Q.png'],
            [68, 'RusLine', '7R.png'],
            [69, 'Bering Air', '8E.png'],
            [70, 'Pacific Coastal Airlines', '8P.png'],
            [71, 'Afriqiyah Airways', '8U.png'],
            [72, 'Eurostar', '9F.png'],
            [73, 'Astra Airlines', 'A2.png'],
            [74, 'Myanmar Airways International', '8M.png'],
            [75, 'Sol Lineas Aereas', '8R.png'],
            [76, 'AccesRail', '9B.png'],
            [77, 'Cape Air', '9K.png'],
            [78, 'Air Moldova', '9U.png'],
            [79, 'Eastar Jet', 'ZE.png'],
            [80, 'Chang An Airlines', '9H.png'],
            [81, 'Southern Air', '9R.png'],
            [82, 'Jet Airways', '9W.png'],
            [83, 'Aeromexico', 'AM.png'],
            [84, 'Alitalia', 'AZ.png'],
            [85, 'Major Airline', 'XX.png'],
            [86, 'Central Mountain Air', '9M.png'],
            [87, 'Avior Airlines', '9V.png'],
            [88, 'Aegean Airlines', 'A3.png'],
            [89, 'Azimut', 'A4.png'],
            [90, 'Air Alps Aviation', 'A6.png'],
            [91, 'Air Berlin', 'AB.png'],
            [92, 'Georgian Airways', 'A9.png'],
            [93, 'American Airlines', 'AA.png'],
            [94, 'Air One', 'AP.png'],
            [95, 'Aerolineas Argentinas', 'AR.png'],
            [96, 'Royal Air Maroc', 'AT.png'],
            [97, 'Armenia Aircompany', 'RM.png'],
            [98, 'Level', 'VK.png'],
            [99, 'SkyUp Airlines', 'PQ.png'],
            [100, 'Linear Air', 'O2.png'],
            [101, 'Air Canada', 'AC.png'],
            [102, 'Belavia', 'B2.png'],
            [103, 'Uni Air', 'B7.png'],
            [104, 'TAAG Angola Airlines', 'DT.png'],
            [105, 'Norwegian Air Shuttle', 'DY.png'],
            [106, 'Thai Express Air Co. Ltd', 'EX.png'],
            [107, 'Azul Brazilian Airlines', 'AD.png'],
            [108, 'East African Safari Air', 'B5.png'],
            [109, 'Eritrean Airlines', 'B8.png'],
            [110, 'Trade Air', 'C3.png'],
            [111, 'Grand China Air', 'CN.png'],
            [112, 'Bringer Air Cargo', 'E6.png'],
            [113, 'Mandarin Airlines', 'AE.png'],
            [114, 'Air France', 'AF.png'],
            [115, 'Air India', 'AI.png'],
            [116, 'AirAsia', 'AK.png'],
            [117, 'Alaska Airlines', 'AS.png'],
            [118, 'Austral Lineas Aereas', 'AU.png'],
            [119, 'Avianca', 'AV.png'],
            [120, 'Finnair', 'AY.png'],
            [121, 'Flybe', 'BE.png'],
            [122, 'Royal Brunei', 'BI.png'],
            [123, 'Inter Air', 'D6.png'],
            [124, 'JetBlue Airways', 'B6.png'],
            [125, 'Caribbean Airlines', 'BW.png'],
            [126, 'Cobalt Air', 'CO.png'],
            [127, 'Aer Lingus', 'EI.png'],
            [128, 'Pegas Fly', 'EO.png'],
            [129, 'Airtran Airways', 'FL.png'],
            [130, 'Seaborne Airlines', 'BB.png'],
            [131, 'Hawkair', 'BH.png'],
            [132, 'Blue Panorama Airlines', 'BV.png'],
            [133, 'Airlines PNG', 'CG.png'],
            [134, 'China Southern Airlines', 'CZ.png'],
            [135, 'JSC Aircompany ATMA', 'IM.png'],
            [136, 'Jetstar Pacific Airlines', 'BL.png'],
            [137, 'Cubana de Aviación', 'CU.png'],
            [138, 'Danish Air Transport', 'DX.png'],
            [139, 'Hong Kong Airlines', 'HX.png'],
            [140, 'Qazaq Air', 'IQ.png'],
            [141, 'Bahrain Air', 'BN.png'],
            [142, 'China Airlines', 'CI.png'],
            [143, 'OpenSkies', 'EC.png'],
            [144, 'Eurowings', 'EW.png'],
            [145, 'Wizz Air', 'W9.png'],
            [146, 'Thai AirAsia', 'FD.png'],
            [147, 'Eva Air', 'BR.png'],
            [148, 'Air China', 'CA.png'],
            [149, 'Cathay Pacific', 'CX.png'],
            [150, 'Severstal Air', 'D2.png'],
            [151, 'Donavia', 'D9.png'],
            [152, 'Eurolot', 'K2.png'],
            [153, 'Air Busan', 'BX.png'],
            [154, 'Chalair Aviation', 'CE.png'],
            [155, 'Adria Airways', 'JP.png'],
            [156, 'Korean Air', 'KE.png'],
            [157, 'China United Airlines', 'KN.png'],
            [158, 'Helijet', 'JB.png'],
            [159, 'BA Cityflyer', 'CJ.png'],
            [160, 'Norwegian Air', 'DN.png'],
            [161, 'SalamAir', 'OV.png'],
            [162, 'Air Dolomiti', 'EN.png'],
            [163, 'Aurigny Air Services', 'GR.png'],
            [164, 'Sky Airline', 'H2.png'],
            [165, 'Lufthansa CityLine', 'CL.png'],
            [166, 'Transasia Airways', 'GE.png'],
            [167, 'Air Greenland', 'GL.png'],
            [168, 'Air Seychelles', 'HM.png'],
            [169, 'Héli Sécurité Hélicopter Airline', 'HS.png'],
            [170, 'Zapways, Inc.', 'R1.png'],
            [171, 'Copa Airlines', 'CM.png'],
            [172, 'Joy Air', 'JR.png'],
            [173, 'Bearskin Airlines', 'JV.png'],
            [174, 'Cambodia Angkor Air', 'K6.png'],
            [175, 'MyWay Airlines', 'MJ.png'],
            [176, 'Peach', 'MM.png'],
            [177, 'AirAsia X', 'D7.png'],
            [178, 'Braathens Regional', 'DC.png'],
            [179, 'AirAsia Japan', 'DJ.png'],
            [180, 'Ethiopian Airlines', 'ET.png'],
            [181, 'Globus Airlines', 'GH.png'],
            [182, 'Air Caledonie', 'TY.png'],
            [183, 'Brit Air', 'DB.png'],
            [184, 'Tigerair Philippines', 'DG.png'],
            [185, 'Emirates', 'EK.png'],
            [186, 'TAME Linea Aerea del Ecuador', 'EQ.png'],
            [187, 'Interstate Airlines', 'I4.png'],
            [188, 'Kyrgyz Air', 'KH.png'],
            [189, 'Condor', 'DE.png'],
            [190, 'Sun-Air of Scandinavia', 'EZ.png'],
            [191, 'Bulgaria Air', 'FB.png'],
            [192, 'Fiji Airways', 'FJ.png'],
            [193, 'Servicios Aéreos de los Andes', 'FP.png'],
            [194, 'Kenmore Air', 'M5.png'],
            [195, 'Delta Air Lines', 'DL.png'],
            [196, 'Uganda Airlines', 'UR.png'],
            [197, 'Chengdu Airlines', 'EU.png'],
            [198, 'Allegiant Air', 'G4.png'],
            [199, 'Juneyao Airlines', 'HO.png'],
            [200, 'NAYSA', 'ZN.png'],
            [201, 'Frontier Airlines', 'F9.png'],
            [202, 'Icelandair', 'FI.png'],
            [203, 'Shanghai Airlines', 'FM.png'],
            [204, 'Ryanair', 'FR.png'],
            [205, 'Firefly', 'FY.png'],
            [206, 'Cargolux', 'CV.png'],
            [207, 'Brindabella Airlines', 'FQ.png'],
            [208, 'I Fly', 'F7.png'],
            [209, 'Gulf Air', 'GF.png'],
            [210, 'Izhavia', 'I8.png'],
            [211, 'LATAM Brasil', 'JJ.png'],
            [212, 'Marsland Aviation', 'M7.png'],
            [213, 'Syphax Airlines', 'FS.png'],
            [214, 'Flydubai', 'FZ.png'],
            [215, 'Go!', 'G8.png'],
            [216, 'Transavia', 'HV.png'],
            [217, 'AirAsia India', 'I5.png'],
            [218, 'Joon', 'JN.png'],
            [219, 'Gol Transportes Aéreos', 'G3.png'],
            [220, 'Air Arabia', 'G9.png'],
            [221, 'SkyGreece Airlines', 'GW.png'],
            [222, 'Hawaiian Airlines', 'HA.png'],
            [223, 'Aurora', 'HZ.png'],
            [224, 'Tigerair Taiwan', 'IT.png'],
            [225, 'Garuda Indonesia', 'GA.png'],
            [226, 'Air Italy', 'IG.png'],
            [227, 'Cayman Airways', 'KX.png'],
            [228, 'Belle Air Europe', 'L9.png'],
            [229, 'Swiss International Air Lines', 'LX.png'],
            [230, 'CanJet', 'C6.png'],
            [231, 'Tianjin Airlines', 'GS.png'],
            [232, 'Himalaya Airlines', 'H9.png'],
            [233, 'Niki', 'HG.png'],
            [234, 'Hahn Air', 'HR.png'],
            [235, 'Iberia', 'IB.png'],
            [236, 'Comair', 'MN.png'],
            [237, 'Air Côte d\'Ivoire', 'HF.png'],
            [238, 'Iran Air', 'IR.png'],
            [239, 'Yemenia', 'IY.png'],
            [240, 'Azerbaijan Airlines', 'J2.png'],
            [241, 'Atlas Global Airlines', 'KK.png'],
            [242, 'Hainan Airlines', 'HU.png'],
            [243, 'Uzbekistan Airways', 'HY.png'],
            [244, 'Berjaya Air', 'J8.png'],
            [245, 'Beijing Capital Airlines', 'JD.png'],
            [246, 'Lion Air', 'JT.png'],
            [247, 'Iberia Express', 'I2.png'],
            [248, 'Solomon Airlines', 'IE.png'],
            [249, 'Jetstar', 'JQ.png'],
            [250, 'Air Serbia', 'JU.png'],
            [251, 'SeaPort Airlines', 'K5.png'],
            [252, 'Druk Air', 'KB.png'],
            [253, 'Air Italy', 'I9.png'],
            [254, 'Japan Airlines', 'JL.png'],
            [255, 'Cathay Dragon', 'KA.png'],
            [256, 'Kuwait Airways', 'KU.png'],
            [257, 'Mauritania Airlines International', 'L6.png'],
            [258, 'Air India Express', 'IX.png'],
            [259, 'Jetlink Express', 'J0.png'],
            [260, 'Afrijet Business Service', 'J7.png'],
            [261, 'B&H Airlines', 'JA.png'],
            [262, 'Air Astana', 'KC.png'],
            [263, 'Komiaviatrans', 'KO.png'],
            [264, 'Arkia', 'IZ.png'],
            [265, 'Northwestern Air', 'J3.png'],
            [266, 'Jazeera Airways', 'J9.png'],
            [267, 'Mango', 'JE.png'],
            [268, 'Belle Air', 'LZ.png'],
            [269, 'Motor Sich Airlines', 'M9.png'],
            [270, 'Blue1', 'KF.png'],
            [271, 'KLM', 'KL.png'],
            [272, 'Penair', 'KS.png'],
            [273, 'Kunming Airlines', 'KY.png'],
            [274, 'Azur Air Ukraine', 'QU.png'],
            [275, 'Liat', 'LI.png'],
            [276, 'Air Malta', 'KM.png'],
            [277, 'Kenya Airways', 'KQ.png'],
            [278, 'Luxair', 'LG.png'],
            [279, 'Avianca Costa Rica', 'LR.png'],
            [280, 'Maya Island Air', 'MY.png'],
            [281, 'Condor', 'DF.png'],
            [282, 'Air Bishkek', 'KR.png'],
            [283, 'El Al Israel Airlines', 'LY.png'],
            [284, 'Middle East Airlines', 'ME.png'],
            [285, 'Air Macau', 'NX.png'],
            [286, 'Transaero Airlines', 'UN.png'],
            [287, 'Lufthansa', 'LH.png'],
            [288, 'Libyan Airlines', 'LN.png'],
            [289, 'LATAM Paraguay', 'PZ.png'],
            [290, 'Tarom', 'RO.png'],
            [291, 'Santa Barbara Airlines', 'S3.png'],
            [292, 'Hex Air', 'UD.png'],
            [293, 'Jin Air', 'LJ.png'],
            [294, 'Xiamen Airlines', 'MF.png'],
            [295, 'Air Freight NZ', 'OG.png'],
            [296, 'MIAT Mongolian Airlines', 'OM.png'],
            [297, 'Air Kyrgyzstan', 'QH.png'],
            [298, 'TACA Airlines', 'TA.png'],
            [299, 'LOT Polish Airlines', 'LO.png'],
            [300, 'Pacific Wings', 'LW.png'],
            [301, 'Olympic Air', 'OA.png'],
            [302, 'Passaredo Linhas Aereas', 'P3.png'],
            [303, 'Pegasus Airlines', 'PC.png'],
            [304, 'Jet2.com', 'LS.png'],
            [305, 'Malaysia Airlines', 'MH.png'],
            [306, 'Air Mauritius', 'MK.png'],
            [307, 'Sky Wings Airlines', 'ND.png'],
            [308, 'Air New Zealand', 'NZ.png'],
            [309, 'Asian Air', 'DM.png'],
            [310, 'Air Madagascar', 'MD.png'],
            [311, 'Silkair', 'MI.png'],
            [312, 'Air Mediterranee', 'ML.png'],
            [313, 'EgyptAir', 'MS.png'],
            [314, 'Czech Airlines', 'OK.png'],
            [315, 'Calm Air International', 'MO.png'],
            [316, 'Portugália', 'NI.png'],
            [317, 'VIM Airlines', 'NN.png'],
            [318, 'Binter Canarias', 'NT.png'],
            [319, 'Precision Air', 'PW.png'],
            [320, 'Wideroe', 'WF.png'],
            [321, 'China Eastern Airlines', 'MU.png'],
            [322, 'Merpati Nusantara Airlines', 'MZ.png'],
            [323, 'Air Vanuatu', 'NF.png'],
            [324, 'Polynesian Airlines', 'OL.png'],
            [325, 'Austrian Airlines', 'OS.png'],
            [326, 'DHL Aero Expreso S.A.', 'D5.png'],
            [327, 'Mokulele Airlines', 'MW.png'],
            [328, 'Nordwind Airlines', 'N4.png'],
            [329, 'Aero Contractors', 'NG.png'],
            [330, 'Andes Lineas Aereas', 'OY.png'],
            [331, 'Rossiya Airlines', 'FV.png'],
            [332, 'LATAM Ecuador', 'XL.png'],
            [333, 'All Nippon Airways', 'NH.png'],
            [334, 'Manx2', 'NM.png'],
            [335, 'Hebei Airlines', 'NS.png'],
            [336, 'Croatia Airlines', 'OU.png'],
            [337, 'Asiana Airlines', 'OZ.png'],
            [338, 'Farelogix Qatar Airways', 'F1.png'],
            [339, 'Spirit Airlines', 'NK.png'],
            [340, 'Air Japan', 'NQ.png'],
            [341, 'Japan Transocean Air', 'NU.png'],
            [342, 'S7 Airlines', 'S7.png'],
            [343, 'Shandong Airlines', 'SC.png'],
            [344, 'Sky Lease I, Inc.', 'GG.png'],
            [345, 'Northwest Airlines', 'NW.png'],
            [346, 'SkyWork Airlines', 'SX.png'],
            [347, 'TRIP Linhas Aéreas', 'T4.png'],
            [348, 'Airnorth', 'TL.png'],
            [349, 'Air Transat', 'TS.png'],
            [350, 'Tibet Airlines', 'TV.png'],
            [351, 'TUI Airlines Netherlands', 'OR.png'],
            [352, 'Indonesia AirAsia', 'QZ.png'],
            [353, 'Aserca Airlines', 'R7.png'],
            [354, 'Atlantic Airways', 'RC.png'],
            [355, 'Air Creebec', 'YN.png'],
            [356, 'Aeropelican Air Services', 'OT.png'],
            [357, 'Provincial Airlines', 'PB.png'],
            [358, 'People\'s Viennaline', 'PE.png'],
            [359, 'Pakistan International Airlines', 'PK.png'],
            [360, 'UIA', 'PS.png'],
            [361, 'Proflight Zambia', 'P0.png'],
            [362, 'SmartWings', 'QS.png'],
            [363, 'Horizon Air', 'QX.png'],
            [364, 'Yakutia Airlines', 'R3.png'],
            [365, 'Royal Flight', 'RL.png'],
            [366, 'Jet Lite', 'S2.png'],
            [367, 'Aerorepublica', 'P5.png'],
            [368, 'Porter Airlines', 'PD.png'],
            [369, 'Air Saint Pierre', 'PJ.png'],
            [370, 'Philippine Airlines', 'PR.png'],
            [371, 'Air Niugini', 'PX.png'],
            [372, 'Stobart Air', 'RE.png'],
            [373, 'Bangkok Airways', 'PG.png'],
            [374, 'China West Air', 'PN.png'],
            [375, 'Qantas', 'QF.png'],
            [376, 'Monacair', 'QM.png'],
            [377, 'BRA', 'TF.png'],
            [378, 'Scoot', 'TR.png'],
            [379, 'Surinam Airways', 'PY.png'],
            [380, 'Camair-Co', 'QC.png'],
            [381, 'UVT Aero', 'RT.png'],
            [382, 'SATA', 'S4.png'],
            [383, 'Saudia', 'SV.png'],
            [384, 'Sun Country Airlines', 'SY.png'],
            [385, 'Syrian Arab Airlines', 'RB.png'],
            [386, 'Rotana Jet', 'RG.png'],
            [387, 'South African Airways', 'SA.png'],
            [388, 'Sudan Airways', 'SD.png'],
            [389, 'Trans Air Congo', 'Q8.png'],
            [390, 'Scandinavian Airlines', 'SK.png'],
            [391, 'Thai Airways', 'TG.png'],
            [392, 'United Airlines', 'UA.png'],
            [393, 'Srilankan Airlines', 'UL.png'],
            [394, 'Citilink Airlines', 'QG.png'],
            [395, 'Qatar Airways', 'QR.png'],
            [396, 'Lao Airlines', 'QV.png'],
            [397, 'Orenair', 'R2.png'],
            [398, 'Royal Nepal Airlines', 'RA.png'],
            [399, 'Tigerair Mandala', 'RI.png'],
            [400, 'Aircalin', 'SB.png'],
            [401, 'XL Airways France', 'SE.png'],
            [402, 'Aeroflot', 'SU.png'],
            [403, 'Tunisair Express', 'UG.png'],
            [404, 'New England Airlines', 'EJ.png'],
            [405, 'Royal Jordanian', 'RJ.png'],
            [406, 'Tradewind Aviation', 'TJ.png'],
            [407, 'LAM Mozambique Airlines', 'TM.png'],
            [408, 'Alitalia CityLiner', 'CT.png'],
            [409, 'Shuttle America', 'S5.png'],
            [410, 'SATA Air Acores', 'SP.png'],
            [411, 'Air Europa', 'UX.png'],
            [412, 'SpiceJet', 'SG.png'],
            [413, 'Conviasa', 'V0.png'],
            [414, 'Vieques Air Link', 'V4.png'],
            [415, 'Virgin Australia', 'VA.png'],
            [416, 'TACV Cabo Verde Airlines', 'VR.png'],
            [417, 'Viva Air', 'VV.png'],
            [418, 'Blue Islands', 'SI.png'],
            [419, 'EasyJet', 'U2.png'],
            [420, 'Tus Airways', 'U8.png'],
            [421, 'Carpatair', 'V3.png'],
            [422, 'Volotea', 'V7.png'],
            [423, 'Valuair', 'VF.png'],
            [424, 'Brussels Airlines', 'SN.png'],
            [425, 'Corsair International', 'SS.png'],
            [426, 'Singapore Airlines', 'SQ.png'],
            [427, 'Tyrolean Airways', 'VO.png'],
            [428, 'Amaszonas', 'Z8.png'],
            [429, 'White Airways', 'WI.png'],
            [430, 'South African Express', 'XZ.png'],
            [431, 'Fortune', 'X1.png'],
            [432, 'Air Namibia', 'SW.png'],
            [433, 'Eastern Airways', 'T3.png'],
            [434, 'Twin Jet', 'T7.png'],
            [435, 'Turkish Airlines', 'TK.png'],
            [436, 'Air Tahiti Nui', 'TN.png'],
            [437, 'Iran Aseman Airlines', 'EP.png'],
            [438, 'Turkmenistan Airlines', 'T5.png'],
            [439, 'Atlantis European Airways', 'TD.png'],
            [440, 'Transavia', 'TO.png'],
            [441, 'Edelweiss Air', 'WK.png'],
            [442, 'Island Air', 'WP.png'],
            [443, 'Air East', 'ER.png'],
            [444, 'TAP Portugal', 'TP.png'],
            [445, 'Air Caraibes', 'TX.png'],
            [446, 'Ural Airlines', 'U6.png'],
            [447, 'Tatarstan Airlines', 'U9.png'],
            [448, 'Tunisair', 'TU.png'],
            [449, 'Scoot', 'TZ.png'],
            [450, 'Air Uganda', 'U7.png'],
            [451, 'Air Austral', 'UU.png'],
            [452, 'VLM Airlines', 'VG.png'],
            [453, 'Air Zimbabwe', 'UM.png'],
            [454, 'Hong Kong Express Airways', 'UO.png'],
            [455, 'US Airways', 'US.png'],
            [456, 'Virgin Atlantic', 'VS.png'],
            [457, 'Aeromar', 'VW.png'],
            [458, 'FlexFlight', 'W2.png'],
            [459, 'Worldspan', '1P.png'],
            [460, 'Bahamasair', 'UP.png'],
            [461, 'Utair', 'UT.png'],
            [462, 'Air Tahiti', 'VT.png'],
            [463, 'Virgin America ', 'VX.png'],
            [464, 'Arik Air', 'W3.png'],
            [465, 'KLM Cityhopper', 'WA.png'],
            [466, 'Vision Airlines', 'V2.png'],
            [467, 'Aerovías DAP', 'V5.png'],
            [468, 'C.A.I. Second', 'VE.png'],
            [469, 'Vietnam Airlines', 'VN.png'],
            [470, 'Great Lakes Airlines', 'ZK.png'],
            [471, 'Vueling', 'VY.png'],
            [472, 'Wizz Air', 'W6.png'],
            [473, 'Aigle Azur', 'ZI.png'],
            [474, 'RwandAir', 'WB.png'],
            [475, 'Sun Express', 'XQ.png'],
            [476, 'Nas Air', 'XY.png'],
            [477, 'Yamal Airlines', 'YC.png'],
            [478, 'Montenegro Airlines', 'YM.png'],
            [479, 'HOP!', 'YS.png'],
            [480, 'Webjet Linhas Aereas', 'WH.png'],
            [481, 'Southwest Airlines', 'WN.png'],
            [482, 'Wizz Air Ukraine', 'WU.png'],
            [483, 'TUI fly', 'X3.png'],
            [484, 'Vladivostok Air', 'XF.png'],
            [485, 'South Airlines', 'YG.png'],
            [486, 'Winair', 'WM.png'],
            [487, 'Westjet', 'WS.png'],
            [488, 'Virgin Australia', 'XR.png'],
            [489, 'Volaris', 'Y4.png'],
            [490, 'Dniproavia', 'Z6.png'],
            [491, 'Cityjet', 'WX.png'],
            [492, 'WOW air', 'X9.png'],
            [493, 'Air Corsica', 'XK.png'],
            [494, 'Shenzhen Airlines', 'ZH.png'],
            [495, 'Regional Express', 'ZL.png'],
            [496, 'Sky Airlines', 'ZY.png'],
            [497, 'Oman Air', 'WY.png'],
            [498, 'KD Air', 'XC.png'],
            [499, 'Air Nostrum', 'YW.png'],
            [500, 'Monarch Airlines', 'ZB.png'],
            [501, 'Equatorial Congo Airlines', 'LC.png'],
            [502, 'Thomson Airways', 'BY.png'],
            [503, 'C.A.I. First', 'XM.png'],
            [504, 'BVI Airways', 'XV.png'],
            [505, 'NordStar', 'Y7.png'],
            [506, 'Avia Traffic Company', 'YK.png'],
            [507, 'Heli Air Monaco', 'YO.png'],
            [508, 'Mesa Airlines', 'YV.png'],
            [509, 'Polet Airlines', 'YQ.png'],
            [510, 'SUN-AIR', 'ZU.png'],
            [511, 'IrAero', 'IO.png'],
            [512, 'Germania', 'ST.png'],
            [513, 'Gambia Bird Airlines', '3G.png'],
            [514, 'BMI Regional', 'BM.png'],
            [515, 'BQB Lineas Aereas', '5Q.png'],
            [516, 'Groznyy Avia', 'ZG.png'],
            [517, 'AirAsia Zest', 'Z2.png'],
            [518, 'Red Wings Airlines', 'WZ.png'],
            [519, 'Republic Airlines', 'YX.png'],
            [520, 'Skippers Aviation', 'HK.png'],
            [521, 'Hunnu Air', 'MR.png'],
            [522, 'ASKY Airlines', 'KP.png'],
            [523, 'Sunwing Airlines', 'WG.png'],
            [524, 'Silver Airways', '3M.png'],
            [525, 'Airlink', '4Z.png'],
            [526, 'Japan Air Commuter', 'JC.png'],
            [527, 'SunExpress Deutschland', 'XG.png'],
            [528, 'HOP!', 'AN.png'],
            [529, 'Jetstar Japan', 'GK.png'],
            [530, 'Wings Air', 'IW.png'],
            [531, 'Kan Air', 'K8.png'],
            [532, 'Norwegian Long Haul', 'DU.png'],
            [533, 'Thai AirAsia X', 'XJ.png'],
            [534, 'Blue Bird Airways', 'BZ.png'],
            [535, 'Batik Air', 'ID.png'],
            [536, 'Sky Express', 'GQ.png'],
            [537, 'Pobeda', 'DP.png'],
            [538, 'Air Leisure', 'AL.png'],
            [539, 'Africa World Airlines', 'AW.png'],
            [540, 'Aerolink Uganda Limited', 'A8.png'],
            [541, 'BB Airways', 'BO.png'],
            [542, 'Cimber', 'QA.png'],
            [543, 'Bek Air', 'Z9.png'],
            [544, 'Insel Air', '8I.png'],
            [545, 'Korongo Airlines', 'ZC.png'],
            [546, 'Orient Thai Airlines', 'OX.png'],
            [547, 'Sriwijaya Air', 'SJ.png'],
            [548, 'Angara Airlines', '2G.png'],
            [549, 'Nok Air', 'DD.png'],
            [550, 'Thai Lion Air', 'SL.png'],
            [551, 'Colorful Guizhou Airlines', 'GY.png'],
            [552, 'Dobrolet', 'QD.png'],
            [553, 'Air Armenia', 'QN.png'],
            [554, 'Air Kiribati Limited', 'IK.png'],
            [555, 'Somon Air', 'SZ.png'],
            [556, 'Aztec Airways', 'AJ.png'],
            [557, '9 Air', 'AQ.png'],
            [558, 'Air Niamey', 'A7.png'],
            [559, 'Aruba Airlines', 'AG.png'],
            [560, 'Australian Airlines', 'AO.png'],
            [561, 'Trans States Airlines', 'AX.png'],
            [562, 'Skymark Airlines', 'BC.png'],
            [563, 'Compagnie Africaine d\'Aviation', 'BU.png'],
            [564, 'Bhutan Airlines', 'B3.png'],
            [565, 'French Blue', 'BF.png'],
            [566, 'La Compagnie', 'B0.png'],
            [567, 'ZanAir', 'B4.png'],
            [568, 'CM Airlines', 'CC.png'],
            [569, 'Bemidji Airlines', 'CH.png'],
            [570, 'Czech Connect Airlines', 'CQ.png'],
            [571, 'TAB - Transportes Aéreos Bolivianos', 'B1.png'],
            [572, 'Iran Air Tours', 'B9.png'],
            [573, 'Corendon Dutch Airlines', 'CD.png'],
            [574, 'China Cargo Airlines', 'CK.png'],
            [575, 'OAG', 'CR.png'],
            [576, 'Tectimes Sudamerica', 'C1.png'],
            [577, 'China Postal Airlines Ltd.', 'CF.png'],
            [578, 'Compass Airlines', 'CP.png'],
            [579, 'Continental Micronesia, Inc.', 'CS.png'],
            [580, 'CEIBA Intercontinental', 'C2.png'],
            [581, 'Cinnamon Air', 'C7.png'],
            [582, 'Douniah Airlines', 'DH.png'],
            [583, 'CommutAir', 'C5.png'],
            [584, 'Cronos Airlines', 'C8.png'],
            [585, 'Norwegian Air', 'DI.png'],
            [586, 'Discovery Airways', 'DO.png'],
            [587, 'easyJet Switzerland', 'DS.png'],
            [588, 'DHL Air Limited', 'D0.png'],
            [589, 'Thomas Cook Airlines Scandinavia', 'DK.png'],
            [590, 'Delta Connection', 'DQ.png'],
            [591, 'Aero-Charter Ukraine', 'DW.png'],
            [592, 'Daallo Airlines', 'D3.png'],
            [593, 'Norwegian Air International', 'D8.png'],
            [594, 'AirExplore', 'ED.png'],
            [595, 'Ruili Airlines', 'DR.png'],
            [596, 'Donghai Airlines', 'DZ.png'],
            [597, 'Alidaunia', 'D4.png'],
            [598, 'East Horizon Airlines', 'EA.png'],
            [599, 'Fly CamInter', 'EF.png'],
            [600, 'Ellinair', 'EL.png'],
            [601, 'Wamos Air', 'EB.png'],
            [602, 'ANA Wings', 'EH.png'],
            [603, 'Empire Airlines', 'EM.png'],
            [604, 'DHL Aviation EEMEA B.S.C.[c)', 'ES.png'],
            [605, 'Eagle Atlantic Airlines', 'E2.png'],
            [606, 'Equaflight Service', 'E7.png'],
            [607, 'ExpressJet', 'EV.png'],
            [608, 'Air Arabia Egypt', 'E5.png'],
            [609, 'City Airways', 'E8.png'],
            [610, 'Far Eastern Air Transport', 'FE.png'],
            [611, 'Freebird Airlines', 'FH.png'],
            [612, 'Fuzhou Airlines', 'FU.png'],
            [613, 'Evelop Airlines', 'E9.png'],
            [614, 'Airshop B.V.', 'FF.png'],
            [615, 'fastjet', 'FN.png'],
            [616, 'Ibex Airlines', 'FW.png'],
            [617, 'Safarilink Aviation', 'F2.png'],
            [618, 'Flair Airlines Ltd.', 'F8.png'],
            [619, 'Safair', 'FA.png'],
            [620, 'Ariana Afghan Airlines', 'FG.png'],
            [621, 'Felix Airways', 'FO.png'],
            [622, 'FedEx', 'FX.png'],
            [623, 'Flyadeal', 'F3.png'],
            [624, 'ABX Air, Inc.', 'GB.png'],
            [625, 'Air Flamenco', 'F4.png'],
            [626, 'Gambia International Airlines', 'GC.png'],
            [627, 'Loong Air', 'GJ.png'],
            [628, 'Vista Georgia', 'GT.png'],
            [629, 'Air Rarotonga', 'GZ.png'],
            [630, 'Ghadames Air Transport', 'G6.png'],
            [631, 'Itek Air', 'GI.png'],
            [632, 'ULS Airlines Cargo', 'GO.png'],
            [633, 'Grant Aviation, Inc.', 'GV.png'],
            [634, 'China Express Airlines', 'G5.png'],
            [635, 'Asia Atlantic Airlines', 'HB.png'],
            [636, 'Taban Airlines', 'HH.png'],
            [637, 'Germania Flug', 'GM.png'],
            [638, 'Aviateca', 'GU.png'],
            [639, 'Jet Express', 'G2.png'],
            [640, 'GoJet Airlines', 'G7.png'],
            [641, 'LGW Luftfahrtgesellschaft Walter', 'HE.png'],
            [642, 'Hellas Jet', 'HJ.png'],
            [643, 'Air Do', 'HD.png'],
            [644, 'Papillon Airways', 'HI.png'],
            [645, 'Amapola Flyg AB', 'HP.png'],
            [646, 'Hahn Air', 'H1.png'],
            [647, 'Taron Avia LLC', 'H7.png'],
            [648, 'IBC Airways', 'II.png'],
            [649, 'Afghan Jet International', 'HN.png'],
            [650, 'North-Wright Airways', 'HW.png'],
            [651, 'Bulgarian Air Charter', 'H6.png'],
            [652, 'Irtysh Air', 'IH.png'],
            [653, 'PT.Trigana Air Service', 'IL.png'],
            [654, 'Apsara International Air', 'IP.png'],
            [655, 'Thomas Cook Airlines Belgium', 'HQ.png'],
            [656, 'Aero4M', 'H4.png'],
            [657, 'Hesa Airlines', 'H8.png'],
            [658, 'Spring Airlines Japan', 'IJ.png'],
            [659, 'NAM Air', 'IN.png'],
            [660, 'Air Indus', 'I6.png'],
            [661, 'AIS Airlines B.V.', 'IS.png'],
            [662, 'Jet Asia Airways', 'JF.png'],
            [663, 'Meraj Air', 'JI.png'],
            [664, 'Vanilla Air', 'JW.png'],
            [665, 'One Jet, Inc.', 'J1.png'],
            [666, 'Jet Ops', 'J6.png'],
            [667, 'JETGO Australia', 'JG.png'],
            [668, 'Jet Time', 'JO.png'],
            [669, 'InterCaribbean Airways', 'JY.png'],
            [670, 'BADR AIRLINES', 'J4.png'],
            [671, 'PT Kal Star Aviation', 'KD.png'],
            [672, 'Air Incheon', 'KJ.png'],
            [673, 'Fuji Dream Airlines', 'JH.png'],
            [674, 'Air Koryo', 'JS.png'],
            [675, 'Jatayu Airlines', 'JZ.png'],
            [676, 'Alaska Seaplane', 'J5.png'],
            [677, 'Aerogaviota', 'KG.png'],
            [678, 'SiAvia', 'KT.png'],
            [679, 'KrasAvia', 'KI.png'],
            [680, 'Asian Express Airline', 'KV.png'],
            [681, 'Topas Co. Ltd.', 'K1.png'],
            [682, 'Air KBZ', 'K7.png'],
            [683, 'Laparkan Airways, Inc.', 'LE.png'],
            [684, 'Loganair', 'LM.png'],
            [685, 'Kharkiv Airlines', 'KW.png'],
            [686, 'Taquan Air', 'K3.png'],
            [687, 'Bul Air', 'LB.png'],
            [688, 'Lao Skyway', 'LK.png'],
            [689, 'Air Lituanica', 'LT.png'],
            [690, 'E-Savtravel', 'L1.png'],
            [691, 'Nippon Cargo Airlines', 'KZ.png'],
            [692, 'ALS Ltd.', 'K4.png'],
            [693, 'AHK Air Hong Kong Limited', 'LD.png'],
            [694, 'Miami Air International', 'LL.png'],
            [695, 'LAN Express', 'LU.png'],
            [696, 'Lynden Air Cargo, LLC', 'L2.png'],
            [697, 'Mega Maldives', 'LV.png'],
            [698, 'Lynx Aviation', 'L3.png'],
            [699, 'Afric Aviation', 'L8.png'],
            [700, 'Miami Air Lease, Inc.', 'MG.png'],
            [701, 'Thomas Cook Airlines', 'MT.png'],
            [702, 'North Flying', 'M3.png'],
            [703, 'Air Service Liege', 'L4.png'],
            [704, 'MNG Airlines', 'MB.png'],
            [705, 'Martinair', 'MP.png'],
            [706, 'Mexicana de Aviación', 'MX.png'],
            [707, 'Mistral Air', 'M4.png'],
            [708, 'Nesma Airlines', 'NA.png'],
            [709, 'Linea Aerea Carguera de Colombia S.', 'L7.png'],
            [710, 'Air Mobility Command', 'MC.png'],
            [711, 'Envoy Air', 'MQ.png'],
            [712, 'MHS Aviation', 'M2.png'],
            [713, 'Amerijet International Inc.', 'M6.png'],
            [714, 'Skypower Express Airways', 'NB.png'],
            [715, 'SkyJet', 'M8.png'],
            [716, 'Cobham Aviation Services Australia', 'NC.png'],
            [717, 'Shaheen Air', 'NL.png'],
            [718, 'Air Iceland', 'NY.png'],
            [719, 'Nolinor Aviation', 'N5.png'],
            [720, 'Nova Airways', 'N9.png'],
            [721, 'Nesma Airlines', 'NE.png'],
            [722, 'Neos', 'NO.png'],
            [723, 'Trans-Mediterranean Airways', 'N2.png'],
            [724, 'Nordic Regional Airline', 'N7.png'],
            [725, 'Boliviana de Aviación', 'OB.png'],
            [726, 'Laudamotion', 'OE.png'],
            [727, 'Aero VIP', 'NJ.png'],
            [728, 'Nile Air', 'NP.png'],
            [729, 'Aerolíneas Mas', 'N3.png'],
            [730, 'National Airlines', 'N8.png'],
            [731, 'Oriental Air Bridge', 'OC.png'],
            [732, 'Hinterland Aviation', 'OI.png'],
            [733, 'Malindo Air', 'OD.png'],
            [734, 'Fly Jamaica Airways', 'OJ.png'],
            [735, 'Chongqing Airlines', 'OQ.png'],
            [736, 'Avianca Brazil', 'O6.png'],
            [737, 'airblue', 'PA.png'],
            [738, 'Polar Airlines', 'PI.png'],
            [739, 'Nauru Airline', 'ON.png'],
            [740, 'Orange Air, LLCN/A', 'O3.png'],
            [741, 'Siam Air', 'O8.png'],
            [742, 'Primera Air', 'PF.png'],
            [743, 'Southern Air Charter', 'PL.png'],
            [744, 'Jet Aviation Business', 'PP.png'],
            [745, 'SkyWest Airlines', 'OO.png'],
            [746, 'Antrak Air', 'O4.png'],
            [747, 'NOVA Airlines', 'O9.png'],
            [748, 'Transavia Denmark', 'PH.png'],
            [749, 'Canaryfly', 'PM.png'],
            [750, 'St Barth Commuter', 'PV.png'],
            [751, 'Polar Air Cargo Worldwide, Inc.', 'PO.png'],
            [752, 'Public Charters', 'P1.png'],
            [753, 'Pascan Aviation', 'P6.png'],
            [754, 'Peruvian Airlines', 'P9.png'],
            [755, 'Jazz', 'QK.png'],
            [756, 'Airkenya Express', 'QP.png'],
            [757, 'Airkenya Express', 'P2.png'],
            [758, 'Small Planet Airlines', 'P7.png'],
            [759, 'Qeshm Air', 'QB.png'],
            [760, 'LASER Airlines', 'QL.png'],
            [761, 'Alliance Airlines', 'QQ.png'],
            [762, 'European Air Transport', 'QY.png'],
            [763, 'Aerolíneas Sosa', 'P4.png'],
            [764, 'Air Mekong', 'P8.png'],
            [765, 'Jet Airways Inc.', 'QJ.png'],
            [766, 'Quikjet Cargo Airlines Pvt. Ltd', 'QO.png'],
            [767, 'Avianca Cargo', 'QT.png'],
            [768, 'Sqiva Sistem', 'Q1.png'],
            [769, 'Qingdao Airlines', 'QW.png'],
            [770, 'Maldivian', 'Q2.png'],
            [771, '40-Mile Air', 'Q5.png'],
            [772, 'Air Liaison', 'Q9.png'],
            [773, 'PT Republic Express Airlines', 'RH.png'],
            [774, 'Kam Air', 'RQ.png'],
            [775, 'Anguilla Air Services, Ltd', 'Q3.png'],
            [776, 'Skytrans Airlines', 'Q6.png'],
            [777, 'French Armed Forces', 'RD.png'],
            [778, 'Skyview Airways Company Limiteddba ', 'RK.png'],
            [779, 'Royal Air Force', 'RR.png'],
            [780, '8165343 Canada Inc. dba Air Canada ', 'RV.png'],
            [781, 'Starlink Aviation', 'Q4.png'],
            [782, 'SkyBahamas Airlines', 'Q7.png'],
            [783, 'Connellan air disaster', 'RF.png'],
            [784, 'Chautauqua Airlines', 'RP.png'],
            [785, 'Sky Regional Airlines', 'RS.png'],
            [786, 'Regent Airways', 'RX.png'],
            [787, 'AirBridgeCargo', 'RU.png'],
            [788, 'Jiangxi Air', 'RY.png'],
            [789, 'RUS Aviation', 'R4.png'],
            [790, 'Tassili Airlines', 'SF.png'],
            [791, 'Lufthansa Systems', 'S1.png'],
            [792, 'Jetairfly', 'TB.png'],
            [793, 'Sansa Airlines', 'RZ.png'],
            [794, 'Jordan Aviation', 'R5.png'],
            [795, 'Sharp Airlines', 'SH.png'],
            [796, 'Sunrise Airways', 'S6.png'],
            [797, 'Air Tanzania', 'TC.png'],
            [798, 'Tailwind Airlines', 'TI.png'],
            [799, 'DOT LT', 'R6.png'],
            [800, 'AIR CAIRO', 'SM.png'],
            [801, 'Starbow', 'S9.png'],
            [802, 'Sky-Taxi', 'TE.png'],
            [803, 'Tandem Aero', 'TQ.png'],
            [804, 'TACA Peru', 'T0.png'],
            [805, 'Raya Airways Sdn. Bhd.dba Raya Airw', 'TH.png'],
            [806, 'T\'way Air', 'TW.png'],
            [807, 'TIK Systems', 'T1.png'],
            [808, 'Myanmar National Airlines', 'UB.png'],
            [809, 'UM Airlines', 'UF.png'],
            [810, 'Almasria Universal Airlines', 'UJ.png'],
            [811, 'Nakina Air Service', 'T2.png'],
            [812, 'LAN Chile Cargo', 'UC.png'],
            [813, 'Atlasjet Ukraine', 'UH.png'],
            [814, 'Urumqi Air', 'UQ.png'],
            [815, 'Air Caucasus', 'UY.png'],
            [816, 'As Avies', 'U3.png'],
            [817, 'Telair International GmbH', 'T8.png'],
            [818, 'Ultimate Jetcharters', 'UE.png'],
            [819, 'Auric Air Services Limited', 'UI.png'],
            [820, 'Helicópteros del Sureste', 'UV.png'],
            [821, 'Buraq Air Transport [BRQ)', 'UZ.png'],
            [822, 'Karinou Airlines', 'U5.png'],
            [823, 'Uni-Top Airlines', 'UW.png'],
            [824, 'Videcom International Limited', 'U1.png'],
            [825, 'VivaAerobus', 'VB.png'],
            [826, 'Volga-Dnepr Airlines', 'VI.png'],
            [827, 'Villa Air Pvt. Ltd. dba Villa Air', 'VP.png'],
            [828, 'Thai Vietjet Air', 'VZ.png'],
            [829, 'Charter Air Transport, Inc.', 'VC.png'],
            [830, 'VietjetAir', 'VJ.png'],
            [831, 'Novoair', 'VQ.png'],
            [832, 'IBS Software Services Americas, Inc', 'V1.png'],
            [833, 'Thai Vietjet Air', 'V9.png'],
            [834, 'Labrador Airways Limited', 'WJ.png'],
            [835, 'Aeropostal Alas de Venezuela', 'VH.png'],
            [836, 'Air Via Ltd.', 'VL.png'],
            [837, 'Vuelos Economicos Centroamericanos', 'VU.png'],
            [838, 'Clairmont Holdings Ltd dba VI Air L', 'V6.png'],
            [839, 'Islena de Inversiones S.A. de C.V.d', 'WC.png'],
            [840, 'World Airways', 'WO.png'],
            [841, 'Iliamna Air Taxi Inc.', 'V8.png'],
            [842, 'Thai Smile', 'WE.png'],
            [843, 'Swiftair', 'WT.png'],
            [844, 'World Ticket Ltd', 'W1.png'],
            [845, 'Cargojet Airways Ltd.', 'W8.png'],
            [846, 'Air Transport Association of Americ', 'XD.png'],
            [847, 'Aero VIPCompanhia Transportes Servi', 'WV.png'],
            [848, 'LC Busre SAC', 'W4.png'],
            [849, 'ARINC[Aeronautical Radio, Inc.)', 'XA.png'],
            [850, 'ExpressJet', 'XE.png'],
            [851, 'South East Asian Airlines [SEAIR)In', 'XO.png'],
            [852, 'Indonesia AirAsia Extra, PT', 'XT.png'],
            [853, 'WOW Air ehf', 'WW.png'],
            [854, 'Mahan Airlines', 'W5.png'],
            [855, 'IATA - Clearing HouseInternational ', 'XB.png'],
            [856, 'Special Ground Handling Service -XH', 'XH.png'],
            [857, 'TEM Enterprises', 'XP.png'],
            [858, 'African Express Airways [K)  Limite', 'XU.png'],
            [859, 'Aeronautical Telecommunications Ltd', 'XI.png'],
            [860, 'SITA - Airlines WorldwideTelecommun', 'XS.png'],
            [861, 'NokScoot', 'XW.png'],
            [862, 'Exec Air, Inc. of Naples', 'X7.png'],
            [863, 'Department of National Defence', 'YF.png'],
            [864, 'Asian Wings Airways Limited', 'YJ.png'],
            [865, 'Air Excursion, LLC', 'X4.png'],
            [866, 'Airmax S.A.', 'X8.png'],
            [867, 'Sunsplash Aviation, LLC.', 'YH.png'],
            [868, 'Perimeter Aviation Ltd.', 'YP.png'],
            [869, 'EuroAtlantic Airways S.A.', 'YU.png'],
            [870, 'Yangtze River Express', 'Y8.png'],
            [871, 'S.C. Ten Airways S.R.L.', 'X5.png'],
            [872, 'Yan Air Ltd', 'YE.png'],
            [873, 'Air Sunshine Inc.', 'YI.png'],
            [874, 'Grand Canyon Airlines, Inc.dba Scen', 'YR.png'],
            [875, 'Travel Technology Interactive SA', 'Y1.png'],
            [876, 'Kish Airlines', 'Y9.png'],
            [877, 'Yeti Airlines Domestic Pvt. Ltd.', 'YT.png'],
            [878, 'Golden Myanmar Airlines Public Co.,', 'Y5.png'],
            [879, 'Skywings Asia Airlines Co., Ltd.', 'ZA.png'],
            [880, 'Air Manasdba Air Manas ltd. Air Com', 'ZM.png'],
            [881, 'JSC Kazaviaspas', 'ZS.png'],
            [882, 'Air Wisconsin Airlines Corporation[', 'ZW.png'],
            [883, 'Azur Air', 'ZF.png'],
            [884, 'Silk Way Airlines', 'ZP.png'],
            [885, 'Titan Airways Limited', 'ZT.png'],
            [886, 'Air Georgian Ltd. dba Air Alliance', 'ZX.png'],
            [887, 'NU-Aero [Pvt) Ltdt/a Fly Africa Zim', 'Z7.png'],
            [888, 'Amadeus IT Group SA', '1A.png'],
            [889, 'Zambezi Airlines', 'ZJ.png'],
            [890, 'Aviacon Zitotrans Air Company JSC', 'ZR.png'],
            [891, 'V Air Corporation', 'ZV.png'],
            [892, 'PM Air LLC', 'Z3.png'],
            [893, 'Premium Jet AG', '0J.png'],
            [894, 'Abacus International Pte. Ltd.', '1B.png'],
            [895, 'Zagros Air Co.', 'Z4.png'],
            [896, 'Hydro - Quebec', '0Q.png'],
            [897, 'Hewlett-Packard [Schweiz) GmbH', '1C.png'],
            [898, 'INFINI Travel Information, Inc.', '1F.png'],
            [899, 'ChallengAir', '1I.png'],
            [900, 'Navitaire Open Skies', '1L.png'],
            [901, 'Radixx Solutions International, Inc', '1D.png'],
            [902, 'Travelport Global Distribution Syst', '1G.png'],
            [903, 'Axess International Network Inc.', '1J.png'],
            [904, 'JSC Transport Automated Information', '1M.png'],
            [905, 'Bird Information Systems Private Li', '1R.png'],
            [906, 'ITA Software Inc.', '1U.png'],
            [907, 'Travelsky Technology Limited', '1E.png'],
            [908, 'JSC \"Sirena-Travel\"', '1H.png'],
            [909, 'Sutra Inc.', '1K.png'],
            [910, 'Navitaire', '1N.png'],
            [911, 'Sabre Inc.', '1S.png'],
            [912, 'Galileo International', '1V.png'],
            [913, 'Sabre Pacific', '1Z.png'],
            [914, 'PT Aerosystems Indonesia', '1T.png'],
            [915, 'Fly Branson Travel dba Branson AirE', '1X.png'],
            [916, 'Deutsche Bahn AG', '2A.png'],
            [917, 'Afrinat International Airlines', '2F.png'],
            [918, 'Air Cargo Carriers, LLC.', '2Q.png'],
            [919, 'Sun d\'Or International Airlines', '2U.png'],
            [920, 'Electronic Data Systems Corporation', '1Y.png'],
            [921, 'Dynamic Airways, LLC', '2D.png'],
            [922, 'Thalys International', '2H.png'],
            [923, 'VIA Rail Canada Inc.', '2R.png'],
            [924, 'Amtrak', '2V.png'],
            [925, 'Chu Kong Passenger Transport Co. Lt', '3A.png'],
            [926, 'Smokey Bay Air, Inc.', '2E.png'],
            [927, 'Redemption Inc.', '2O.png'],
            [928, 'Kinda Airlines', '2S.png'],
            [929, 'PT. My Indo Airlines', '2Y.png'],
            [930, 'Calima Aviacion S.L', '3C.png'],
            [931, 'Cargo Three Inc. dba Pan Air Cargo', '3J.png'],
            [932, 'Passaredo Transportes Aereos S.A.', '2Z.png'],
            [933, 'DoKaSch', '3D.png'],
            [934, 'Air Urga', '3N.png'],
            [935, 'Malawian Airlines', '3W.png'],
            [936, 'Travel Service Polska Sp. z.o.o.', '3Z.png'],
            [937, 'LAN COLOMBIA AIRLINES', '4C.png'],
            [938, 'Pacific Airways Inc.', '3F.png'],
            [939, 'Tarco Air', '3T.png'],
            [940, 'Premier Trans Aire Inc.', '3X.png'],
            [941, 'Aero Transporte S.A.', '4A.png'],
            [942, 'Stabo Air Limited', '4E.png'],
            [943, 'IHY Izmir Havayollari A.S.', '4I.png'],
            [944, 'TNT Airways', '3V.png'],
            [945, 'Kartika Airlines', '3Y.png'],
            [946, 'Boutique Air', '4B.png'],
            [947, 'Air City', '4F.png'],
            [948, 'Kenn Borek Air Ltd.', '4K.png'],
            [949, 'Travel Air', '4P.png'],
            [950, 'United Airways Bangladesh Ltd', '4H.png'],
            [951, 'Palau National Airlines', '4L.png'],
            [952, 'CJSC Royal Flight airlines', '4R.png'],
            [953, 'Mercury Air Cargo, Inc.', '4X.png'],
            [954, 'Bassaka Air Limited', '5B.png'],
            [955, 'Fly One', '5F.png'],
            [956, 'Air North Charter and Training Ltd.', '4N.png'],
            [957, 'Solar Cargo, C.A.', '4S.png'],
            [958, 'Airbus Transport International', '4Y.png'],
            [959, 'Aerolitoral S.A. de C.V.', '5D.png'],
            [960, '540 Ghana Ltd.', '5G.png'],
            [961, 'Hi Fly Ltd', '5M.png'],
            [962, 'Lignes Aeriennes Congolaises', '4V.png'],
            [963, 'Alpine Aviation Inc.', '5A.png'],
            [964, 'Siam Ga Co. Ltd.', '5E.png'],
            [965, 'Alsa Grupo SLU', '5I.png'],
            [966, 'Rutas Aereas, C.A. dba  RUTACA', '5R.png'],
            [967, 'Everts Air Cargo', '5V.png'],
            [968, 'Hi Fly', '5K.png'],
            [969, 'Global Aviation Services Group', '5S.png'],
            [970, '5W-Rail&Shuttle', '5W.png'],
            [971, 'CemAir', '5Z.png'],
            [972, 'Air Timor', '6C.png'],
            [973, 'Air Alsie', '6I.png'],
            [974, 'Transportes Aéreos Regionales', '5U.png'],
            [975, 'UPS', '5X.png'],
            [976, 'Armenia Airways', '6A.png'],
            [977, 'Travel Service Slovensko', '6D.png'],
            [978, 'Solaseed Air', '6J.png'],
            [979, 'Zacarias Moreno', '6M.png'],
            [980, 'Atlas Air', '5Y.png'],
            [981, 'TUIfly Nordic', '6B.png'],
            [982, 'Sun Air Express', '6G.png'],
            [983, 'Kyrgyz Trans Avia', '6K.png'],
            [984, 'Niger Airlines', '6N.png'],
            [985, 'Air Cargo Germany', '6U.png'],
            [986, 'Aklak Air', '6L.png'],
            [987, 'Orbest', '6O.png'],
            [988, 'AVANZA', '6V.png'],
            [989, 'StarFlyer', '7G.png'],
            [990, 'Travel Service', '7O.png'],
            [991, 'Ryan Air Service', '7S.png'],
            [992, 'Air Mandalay', '6T.png'],
            [993, 'Euro-Asia Air', '6Z.png'],
            [994, 'MAYAir', '7M.png'],
            [995, 'Air Panama', '7P.png'],
            [996, 'Trenitalia', '7T.png'],
            [997, 'Halcyonair', '7Z.png'],
            [998, 'Sylt Air GmbH', '7E.png'],
            [999, 'Pan American World Airways', '7N.png'],
            [1000, 'Elite Airways', '7Q.png'],
            [1001, 'Alpha Air Transport', '7U.png'],
            [1002, 'Panama Airways', '8A.png'],
            [1003, 'FITS Aviation [Pvt) Ltd', '8D.png'],
            [1004, 'Mann Yadanarpon Airlines', '7Y.png'],
            [1005, 'Business Air Co Ltd', '8B.png'],
            [1006, 'STP Airways', '8F.png'],
            [1007, 'EcoJet', '8J.png'],
            [1008, 'TurboJET', '8S.png'],
            [1009, 'Eaglexpress Air Charter Sdn.Bhd.dba', '9A.png'],
            [1010, 'Air Transport International L.L.C.', '8C.png'],
            [1011, 'Mid Africa Aviation', '8G.png'],
            [1012, 'K-Mile Air Co. Ltd', '8K.png'],
            [1013, 'Air Tindi', '8T.png'],
            [1014, 'Spring Airlines', '9C.png'],
            [1015, 'Alliance Air', '9I.png'],
            [1016, 'BH Air', '8H.png'],
            [1017, 'Regional Air Services', '8N.png'],
            [1018, 'Private Wings', '8W.png'],
            [1019, 'Endeavor Air', '9E.png'],
            [1020, 'Dana Airlines Limited', '9J.png'],
            [1021, 'Air Arabia Jordan', '9P.png'],
            [1022, '9G Rail', '9G.png'],
            [1023, 'West Link Airlines', '9L.png'],
            [1024, 'Caicos Express Airways', '9Q.png'],
            [1025, 'Executive Express Aviation LLC dbaS', '9X.png'],
            [1026, 'SW Italia s.p.a.', 'IU.png'],
            [1027, 'Nomad Aviation [PTY) Ltd.', 'N6.png'],
            [1028, 'Tropic Air Limited', '9N.png'],
            [1029, 'Southern Air Inc.', '9S.png'],
            [1030, 'Vistara', 'UK.png'],
            [1031, 'Sounds Air Travel & Tourism Ltd.', 'S8.png'],
            [1032, 'FlyCorporate', 'FC.png'],
            [1033, 'Guangxi Beibu Gulf Airlines Co., Lt', 'GP.png'],
            [1034, 'ACT Havayollari A.S.', '9T.png'],
            [1035, 'Wings of Lebanon S.a.l', 'W7.png'],
            [1036, 'Conquest Air, Inc.', 'C4.png'],
            [1037, 'Aerotranscargo', 'F5.png'],
            [1038, 'Ningxia Cargo Airlines CO.,LTD', 'HT.png'],
            [1039, 'Regional Jet OÜ', 'EE.png'],
            [1040, 'ATA Airlines', 'I3.png'],
            [1041, 'Major Airline', 'YY.png'],
            [1042, 'Russian Railways', 'R0.png'],
            [1043, 'JetHunter', '01.png'],
            [1044, 'Up Israel', '86.png'],
            [1045, 'Buta Airways', '55.png'],
            [1046, 'Ernest Airline', 'EG.png'],
            [1047, 'SCAT', 'DV.png'],
            [1048, 'Smartavia (Nordavia)', '5N.png'],
        ];
    }
}
